
FROM ubuntu:18.04
COPY rust-toolchain /tmp/rust-toolchain
RUN apt-get update && apt-get install -y libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make curl openssh-client
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(cat /tmp/rust-toolchain)
ENV PATH="/root/.cargo/bin:${PATH}"
ENV NEON_REVISION="25f8005d150e5bf57ab135b21b101c64b13c3aca"
RUN rustup component add rustfmt

