[package]
name = "solana-runtime"
version = "1.8.12"
description = "Solana runtime"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-runtime"
edition = "2018"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.1"
blake3 = "0.3.7"
bv = { version = "0.11.1", features = ["serde"] }
byteorder = "1.3.4"
bzip2 = "0.3.3"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
crossbeam-channel = "0.4"
clickhouse = "0.8.1"
# crossbeam-channel = "0.5"
dir-diff = "0.3.2"
flate2 = "1.0.14"
fnv = "1.0.7"
itertools = "0.9.0"
lazy_static = "1.4.0"
libc = "0.2.81"
libloading = "0.6.2"
log = "0.4.11"
memmap2 = "0.1.0"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
num_cpus = "1.13.0"
ouroboros = "0.10.0"
once_cell = "1.8.0"
rand = "0.7.0"
rayon = "1.5.0"
regex = "1.3.9"
serde = { version = "1.0.122", features = ["rc"] }
serde_derive = "1.0.103"
solana-config-program = { path = "../programs/config", version = "=1.8.12" }
solana-compute-budget-program = { path = "../programs/compute-budget", version = "=1.8.12" }
solana-ed25519-program = { path = "../programs/ed25519", version = "=1.8.12" }
solana-frozen-abi = { path = "../frozen-abi", version = "=1.8.12" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.8.12" }
solana-logger = { path = "../logger", version = "=1.8.12" }
solana-measure = { path = "../measure", version = "=1.8.12" }
solana-metrics = { path = "../metrics", version = "=1.8.12" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.8.12" }
solana-sdk = { path = "../sdk", version = "=1.8.12" }
solana-secp256k1-program = { path = "../programs/secp256k1", version = "=1.8.12" }
solana-stake-program = { path = "../programs/stake", version = "=1.8.12" }
solana-vote-program = { path = "../programs/vote", version = "=1.8.12" }
symlink = "0.1.0"
tar = "0.4.37"
tempfile = "3.1.0"
thiserror = "1.0"
zstd = "0.5.1"
tokio = { version = "1.0", features = ["full"] }
backoff = "0.3"
futures-util = "0.3"
generic-array = { version = "0.14.4", default-features = false, features = ["serde", "more_lengths"] }
clap = "2.33.1"
hex = "0.4.3"
rlp = "0.5"

[dependencies.evm-loader]
git = "https://github.com/neonlabsorg/neon-evm/"
branch = "ci-tracing-api"

[dependencies.evm]
git = "https://github.com/neonlabsorg/evm"
branch = "ci-tracing-api"

[lib]
crate-type = ["lib"]
name = "solana_runtime"

[dev-dependencies]
assert_matches = "1.3.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
