[package]
name = "solana-bpf-rust-big-mod-exp"
version = "1.15.0"
description = "Solana BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-rust-big-mod-exp"
edition = "2021"

[dependencies]
num-bigint = "0.4.3"
serde_json = "1.0.56"
array-bytes = "=1.4.1"
serde = { version = "1.0.112", features = ["derive"] }
solana-program = { path = "../../../../sdk/program", version = "=1.15.0" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
